/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.carrito.view;

import ec.edu.ups.carrito.controllers.ProductoController;

/**
 *
 * @author USER
 */
public class PrincipalView extends javax.swing.JFrame {
    
    private CrearProductoView crearProductoView;
    private BuscarProductoView buscarProductoView;
    private ActualizarProductoView actualizarProductoView;
    private EliminarProductoView eliminarProductoView;
    
    private ProductoController productoController;

    /**
     * Creates new form NewMDIApplication
     */
    public PrincipalView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        productoMenu = new javax.swing.JMenu();
        crearProductoMenu = new javax.swing.JMenuItem();
        buscarProductoMenu = new javax.swing.JMenuItem();
        eliminarProductoMenu = new javax.swing.JMenuItem();
        actualizarProductosMenu = new javax.swing.JMenuItem();
        carritoMenu = new javax.swing.JMenu();
        agregarCarritoMenu = new javax.swing.JMenuItem();
        eliminarCarritoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 250));
        setPreferredSize(new java.awt.Dimension(440, 405));

        menuBar.setBackground(new java.awt.Color(102, 102, 255));

        productoMenu.setMnemonic('f');
        productoMenu.setText("Productos");

        crearProductoMenu.setMnemonic('o');
        crearProductoMenu.setText("Crear");
        crearProductoMenu.addActionListener(this::crearProductoMenuActionPerformed);
        productoMenu.add(crearProductoMenu);

        buscarProductoMenu.setMnemonic('s');
        buscarProductoMenu.setText("Buscar");
        buscarProductoMenu.addActionListener(this::buscarProductoMenuActionPerformed);
        productoMenu.add(buscarProductoMenu);

        eliminarProductoMenu.setMnemonic('a');
        eliminarProductoMenu.setText("Eliminar");
        eliminarProductoMenu.addActionListener(this::eliminarProductoMenuActionPerformed);
        productoMenu.add(eliminarProductoMenu);

        actualizarProductosMenu.setMnemonic('x');
        actualizarProductosMenu.setText("Actualizar");
        actualizarProductosMenu.addActionListener(this::actualizarProductosMenuActionPerformed);
        productoMenu.add(actualizarProductosMenu);

        menuBar.add(productoMenu);

        carritoMenu.setMnemonic('e');
        carritoMenu.setText("Carrito");

        agregarCarritoMenu.setMnemonic('t');
        agregarCarritoMenu.setText("Agregar");
        carritoMenu.add(agregarCarritoMenu);

        eliminarCarritoMenu.setMnemonic('y');
        eliminarCarritoMenu.setText("Eliminar");
        carritoMenu.add(eliminarCarritoMenu);

        menuBar.add(carritoMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProductosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductosMenuActionPerformed
        if(actualizarProductoView == null || !actualizarProductoView.isVisible()){
            actualizarProductoView = new ActualizarProductoView();
            actualizarProductoView.setVisible(true);
            desktopPane.add(actualizarProductoView);
        }
    }//GEN-LAST:event_actualizarProductosMenuActionPerformed

    private void crearProductoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoMenuActionPerformed
        // TODO add your handling code here:
        if(crearProductoView == null || !crearProductoView.isVisible()){
            crearProductoView = new CrearProductoView();
            productoController = new ProductoController(crearProductoView);
            crearProductoView.setVisible(true);
            desktopPane.add(crearProductoView);
        }
    }//GEN-LAST:event_crearProductoMenuActionPerformed

    private void buscarProductoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoMenuActionPerformed
        if(buscarProductoView == null || !buscarProductoView.isVisible()){
            buscarProductoView = new BuscarProductoView();
            buscarProductoView.setVisible(true);
            desktopPane.add(buscarProductoView);
        }
    }//GEN-LAST:event_buscarProductoMenuActionPerformed

    private void eliminarProductoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoMenuActionPerformed
        if(eliminarProductoView == null || !eliminarProductoView.isVisible()){
            eliminarProductoView = new EliminarProductoView();
            eliminarProductoView.setVisible(true);
            desktopPane.add(eliminarProductoView);
        }
    }//GEN-LAST:event_eliminarProductoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarProductosMenu;
    private javax.swing.JMenuItem agregarCarritoMenu;
    private javax.swing.JMenuItem buscarProductoMenu;
    private javax.swing.JMenu carritoMenu;
    private javax.swing.JMenuItem crearProductoMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminarCarritoMenu;
    private javax.swing.JMenuItem eliminarProductoMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productoMenu;
    // End of variables declaration//GEN-END:variables

}
